version: '3.7'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    entrypoint: ["npx", "prisma", "migrate", "dev", " --name", "init", ";", "npm", "start"]
    container_name: api
    volumes:
      - ./api:/app
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=mysql://root@database:3306/grade_system
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.4.2
    container_name: database
    ports:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "grade_system"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "dev"]
    container_name: web
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - api
      